flags: {}
extra-package-dbs: []
packages:
- '.'
extra-deps:
- amazonka-1.4.4.2
- amazonka-core-1.4.4
- amazonka-ec2-1.4.4
- http-client-0.5.4
- http-client-tls-0.3.3
- http-conduit-2.2.3
resolver: lts-7.12
